### ISSUE TITLE
EvE fittings no longer work

### ISSUE THREAD

**Issue by Dharr-Guartonzec** [shibdib/API-Registration-Mod-Revisited#3]
If [evefit][Title, Title][/evefit] is still the right syntax, that does not work anymore compared to Cyerus's original mod.

**Comment by shibdib** [comment]
Fixed with [#8295f4a](https://github.com/shibdib/API-Registration-Mod-Revisited/commit/8295f4a9bb4d7e7dd7c31191a9178365eaabc21d#diff-48171f3b9c0d1121081f697ce610f63d)

to manually fix this go to /styles/prosilver/template and copy the eveapi_fitting.css and eveapi_fitting.js files to whatever theme the one your using is built on.
